playground/demobookapp/__init__.py
# import flask - from the package import class
from flask import Flask, render_template

from flask_bootstrap import Bootstrap

app = Flask(__name__)
bootstrap = Bootstrap(app)

# create a function that creates a web application
# note that a web server will run this web application
def create_app():
    app.debug = True
    app.secret_key = "051ef4a7c70f5f5ca0817a81e202cbe09ce06febab0f5004936be43bbebb26c3"

    # initialize db with flask app

    # importing modules here to avoid circular references, register blueprints of routes
    from . import views

    app.register_blueprint(views.urlmanager)

    # app.register_blueprint(admin.bp)
    return app


@app.errorhandler(404)
# inbuilt function which takes error as parameter
def not_found(e):
    return render_template("404.html")


@app.errorhandler(500)
def internal_error(e):
    return render_template("500.html")

playground/demobookapp/views.py
from flask import Blueprint, render_template
import sys, time

urlmanager = Blueprint("urlmanagers", __name__)


@urlmanager.route("/api/playground/")
def index():
    return render_template(
        "index.html",
        contents=f"{time.ctime()},{sys.path}",
    )


@urlmanager.route("/api/playground/about/")
def about():
    return render_template("aboutus.html")

playground/demobookapp/templates/aboutus.html
{% extends 'base.html' %}

{% block main %}
<h1>About Us</h1>
<div class="jumbotron">
    <p>
        Some info about us here
    </p>
</div>
{% endblock %}

playground/demobookapp/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <title>Demo Book App</title>
</head>

<body>
    <header>
        <!-- Navigationbar content -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="/">Demo's Books</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{{ url_for('urlmanagers.index') }}">Home <span
                                class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('urlmanagers.about') }}">About Us</a>
                    </li>

                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" name="searchterm" type="search" placeholder="Search with ISBN"
                        aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </nav>
        <!-- End of Navigation bar content-->

        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <div class="alert alert-primary" role="alert">
            {% for message in messages %}
            {{ message }}
            {% endfor %}
        </div>
        {% endif %}
        {% endwith %}
    </header>




    <!-- main page content goes in container -->
    <div class="container-fluid">
        <main>
            {% block main %}{% endblock %}
        </main>
    </div>

    <footer class="footer mt-auto py-3 bg-dark">
        <div class="container">
            <span class="text-muted">Copyright © 2021 Demo's Book App.</span>
        </div>
    </footer>

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
        crossorigin="anonymous"></script>
</body>

</html>

playground/demobookapp/templates/index.html
{% extends 'base.html' %}

{% block main %}
<!-- Overlay card-->
<div class="card">
    <div class="card bg-dark text-white">
        <img src="https://southwestdesertlover.files.wordpress.com/2014/03/crocus-in-snow.jpg" width="360px"
            height="460px" class="card-img" alt="background image">
        <div class="card-img-overlay">
            <!-- Carousel showing book picks of the month -->
            <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img src="https://wallpapertag.com/wallpaper/full/6/a/f/605157-tropical-island-desktop-backgrounds-1920x1200-laptop.jpg"
                            width="360px" height="460px" class="d-block mx-auto pb-5">
                    </div>
                    <div class="carousel-item">
                        <img src="https://getwallpapers.com/wallpaper/full/b/c/5/959971-tropical-island-sunset-wallpaper-1920x1080-htc.jpg"
                            width="360px" height="460px" class="d-block mx-auto pb-5">
                    </div>
                    <div class="carousel-item">
                        <img src="https://www.101destinations.com/wp-content/uploads/2015/07/tropical-islands-resort-tropical-sea.jpg"
                            width="360px" height="460px" class="d-block mx-auto pb-5">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
            <!-- End of Carousel showing book picks of the month -->
        </div>
    </div>

</div>
<!-- End of overlay card-->
<br>
<div>{{contents}}</div>
<br>
<div class="container">
    <!-- Card group showing top book categories -->
    <div class="card text-center">
        <div class="row">
            <div class="col-sm card">
                <img src="https://zoozel.ru/gallery/images/1212952_foto-ostrova.jpg" class="card-img-top">

                <div class="card-body">
                    <h5 class="card-title">category name</h5>
                    <p class="card-text">category description</p>
                    <a href="/" class="btn btn-primary">Browse</a>


                </div>
            </div>
        </div>
    </div>
    <!-- End of Card group showing top book categories -->

</div>
<br>

{% endblock %}